### ISSUE TITLE
Understand and begin re-imagining the fleetcomp input generation script 

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#10]
- [x] Understand the python script in https://github.com/arfc/fleetcomp that generates the input xml file. 
- [x] Then add a template file defining the Cycamore:Reactor inputs to help the python script create Cycamore:Reactor based simulations rather than Brightlite based simulations.

**Comment by FlanFlanagan** [comment]
Is this to update from Bright-lite to a recipe reactor?

**Comment by katyhuff** [comment]
exactly. (nothing wrong with bright-lite, we just want to make sure that the recipe-reactor version of this input can succeed)!

**Comment by gyutaepark** [comment]
- [] Add reactor waste output composition to template script
- [] If any output compositions are missing from the vision recipes file. Use origen to find them
