### ISSUE TITLE
Generate fresh and spent fuel recipes for the US fleet

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#11]
- [ ] Work with others to determine the appropriate range of burnups to represent
- [ ] Find (online) or generate (with origen) fresh and spent fuel recipes for a range of burnups

**Comment by gyutaepark** [comment]
@katyhuff Requesting the spreadsheet with origen data
Thank you :)

**Comment by katyhuff** [comment]
closed with preference for duplicate #23 .
