### ISSUE TITLE
80 -> 800k error

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#18]
The bug we looked at the other day, where there was an order of magnitude error in the power generation graph.... it should be fixed with a (single, atomic) pull request. Use a separate branch, please, so that only this change is present in the PR.

**Comment by gyutaepark** [comment]
Ooops, I should have done this on the day...
I'll do so right away.
Thank you

**Comment by gyutaepark** [comment]
Actually, it seems like the bug was only present on the `develop` branch.
The master branch does not have this issue. I must have accidentally added an extra zero after merging the most recent PR.
I'll close this issue now since it wasn't actually an issue for `master` branch.

**Comment by gyutaepark** [comment]
Oops, I've now really understood what you've meant.
I'll undo that commit with the CF fix and make it into a now PR

**Comment by gyutaepark** [comment]
The fix is now performed in #20
