### ISSUE TITLE
Write a report for Predicting the Past work

### ISSUE THREAD

**Issue by gyutaepark** [arfc/predicting-the-past#25]
Write a report for Predicting-the-past in the US region.
Report should contain:
- A methodology with explanation of what functions were used and how they work
- A result section with results of the simulation
- A future works section that outlines future goals for this repository
- A reference section for all the sources used
- A section that explains xml inclusion

**Comment by gyutaepark** [comment]
This issue will be closed with merging PR #26

**Comment by gyutaepark** [comment]
Report is written for the US.
Now awaiting review from Teddy

**Comment by gyutaepark** [comment]
Report is written for Europe.

**Comment by katyhuff** [comment]
can be closed after #32 and #33 are closed.

**Comment by gyutaepark** [comment]
#32 and #33 are closed. 
This issue will now close as well.
