### ISSUE TITLE
Reactor information missing

### ISSUE THREAD

**Issue by gyutaepark** [arfc/predicting-the-past#27]
The `reactors_pris_2016.csv` file available in arfc BOX does not provide all the information necessary for a successful input file creation for _CYCLUS_. I've recognized that Teddy has used certain values for the missing data but am not sure where some of the data is from.

Do you happen to know where I may be able to get the following information for the following reactor types?
Information
- number of assemblies
- assembly size (mass)

Reactor Type
- WCR
- GCR
- FBR
- LWGR

I was unable to find any from the picture of the book that Teddy has posted on arfc slack. Any help would be greatly appreciated.

**Comment by gyutaepark** [comment]
Or should I assume that these reactors are similar enough to PWR and use what I have regarding PWRs?

**Comment by katyhuff** [comment]
OECD NEA has benchmarks for many of these reactor types (e.g. HTGR) ... [https://www.osti.gov/scitech/biblio/1185411](https://www.osti.gov/scitech/biblio/1185411)

The acronyms are a little ambiguous to me, as currently stated.
- GCR is almost certainly "gas cooled reactor" though the main GEN-IV gas-cooled design is usually abbreviated HTGR. Which gas reactor, specifically, are we talking about.
- FBR = fast burner? fast breeder?
- WCR = water cooled reactor? This can be approximated as either BWR or PWR unless you have additional information about the particular reactor (is it russian? in that case, it's probably a VVER).
- LWGR = this one is better known as the RBMK.

**Comment by katyhuff** [comment]
Please close this once the question has been answered.

**Comment by gyutaepark** [comment]
I'll do that. Thank you!

**Comment by jbae11** [comment]
@gyutaepark 
GCR - MAGNOX by UK
FBR - SFR breeder reactor  (most of them except for Russia, I think, are experimental ones)
WCR - in this context is the Egyptian Al Dabaa reactors, which are VVER-1200s

Check out the book `Nuclear Fission Reactors`
both this book and the reference professor huff mentioned are in zotero under fuelcycle - benchmarks

**Comment by gyutaepark** [comment]
I've found out the reactor specifications for the most commonly used reactors. 
This addition is shown in 
https://github.com/arfc/predicting-the-past/commit/a0855d38218c55edadd0f61e4f30fc79cab678b9

**Comment by gyutaepark** [comment]
Closing with #35
