### ISSUE TITLE
Install anaconda on your virtual machine

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#3]
Go to https://www.continuum.io/downloads and follow the linux (or command line) instructions. This will likely have you download a file and execute a script. The download may be one of the commands it tells you to execute (wget, curl). So, don't stress if you don't click something to download it.

**Comment by eriewski** [comment]
Would you prefer that I install Linux 2 or Linux 3?

**Comment by katyhuff** [comment]
Python 3. (note, someday when you feel the need to have both on your machine at once, you can use "conda env". Let me know if you ever need help with that!)
