### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by gyutaepark** [arfc/predicting-the-past#31]
@katyhuff @jbae11 @eriewski @gonuke 

Hi, this is Gyutae Park. I am the undergraduate student that is working under Professor Huff. I've heard from Teddy (Jin Whan Bae) that Professor Wilson was planning to make Eric work on Predicting-the-past repository. 

I've made this issue to note the current status and future goals that this issue has so that Eric can successfully continue (if he desires) from where I have had to stop. I am currently not working on this repository.

At this moment, this repository has finished Predicting-the-past analysis for the US region. This is available in master branch. A report of what I've done, the assumptions made, and the analysis performed is all available in `US.ipynb` file. 

Currently, the Europe simulation lacks specifications for GCRs, Candus, and other reactors. I've used PWR specifications instead. The results and the analysis done is available in the Europe_test branch.

Potential future goals have also been outlined in the Issues.

If you have any questions regarding the repository or the work that I have done, please let me know.

Thank you

**Comment by gonuke** [comment]
Thanks for this very helpful summary.  Are there others in ARFC planning to continue on this?

**Comment by katyhuff** [comment]
We're definitely looking forward to have Eric move it forward at Wisconsin! 

As far as ARFC intentions, GyuTae is likely to pick this back up at some point to use/improve this data set as part of his GIS work. That is, to demonstrate his GIS toolkit addition, I'm hoping he can add lat-long data to each of these reactors and the result of a simulation with all of them can include a map with their positions. If any other undergrads can be conscripted to contribute, I may direct them in this general direction in case Eric can use some help.

**Comment by eriewski** [comment]
@gyutaepark  Thank you very much for the summary.
