### ISSUE TITLE
Merge europe_test into master

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#32]
- [x] Merge europe_test into master to reflect that #21 has been closed.
- [x] Clean up (delete) deprecated branches (europe and europe_test)
- [x] If necessary, open issues to indicate what work is remaining on that effort (see #21)

**Comment by gyutaepark** [comment]
Europe test has been merged into Europe branch and is now deleted.

**Comment by gyutaepark** [comment]
europe branches are now merged to master branch.

**Comment by gyutaepark** [comment]
I've made #37 and #36 to indicate remaining work for the future.
