### ISSUE TITLE
Review Status of US report and EU report 

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#33]
Once #32 is complete, @katyhuff should review the US.ipynb and europe.ipynb files, considering how to archive them as 'living reports' more officially than the current state.

**Comment by gyutaepark** [comment]
@katyhuff 
Hello! I've finished the reports for US and europe regions.
Please note that the files to review are:
`UNITED_STATES.ipynb` and `europe.ipynb`.

**Comment by katyhuff** [comment]
Suggestion, regarding living reports. I have now (finally) created a template for reports: http://arfc.npre.illinois.edu/research/reports/ . We could have "major versions" of this document archived as reports, while "minor versions" won't need to be archived.

**Comment by katyhuff** [comment]
Excited to look this over, though it may be a week or so before I have time.

**Comment by gyutaepark** [comment]
#42 has been closed and merged.
This issue will now close.
