### ISSUE TITLE
cool_spent_uox

### ISSUE THREAD

**Issue by jbae11** [arfc/predicting-the-past#48]
Dearest @gyutaepark,
I am wondering why you'd need the recipe `cool_spent_uox`, since Cyclus can do decay. Considering that you have the option to choose from various burnups, and perhaps for future implementation purposes, wouldn't it make sense for Cyclus to do decay calculations than manually setting what the 'cooled' composition would be?

I'd like to hear what you think.
Thanks

**Comment by jbae11** [comment]
@gyutaepark  Yup. It should probably be just getting rid of the recipe definition in the storage?

**Comment by gyutaepark** [comment]
Sounds like a great idea!
I can make a small section on the comparison between cool_spent_uox and Cyclus decay.
Once I have an input file with Cyclus decay, comparison should be straight-forward.

**Comment by gyutaepark** [comment]
Good point @jbae11 . I've checked the recipe's file.

At this moment, the recipe used for cool_spent_uox uses the spent fuel recipe.
Thus, implementing enabling Cyclus decay to our spent fuel would not be an addition of a feature but a amendment of a bug.

Sadly, this means that we cannot use the two different input files (with decay enabled/ decay disabled) as a benchmarking tool (@gonuke )

Thanks for pointing this out @jbae11!

**Comment by gonuke** [comment]
no worries - good to know!

**Comment by jbae11** [comment]
@gonuke On a different note, it would be nice to do a benchmarking of the Cyclus decay function with another decay computation

**Comment by gyutaepark** [comment]
#55 enables cyclus decay.
This issue is now closed.
