### ISSUE TITLE
Run the Cycamore input files

### ISSUE THREAD

**Issue by katyhuff** [arfc/predicting-the-past#8]
For a few of the Cycamore input files (in the cycamore input directory... these are present on your computer once you have cloned cycamore, but can also be found mirrored online here https://github.com/cyclus/cycamore/tree/develop/input), try running them. 

- [x] decide which execution flags to use when running cyclus (should you use -i to indicate the file? -o to name the output file?) . Report your decision in this issue.
- [x] Execute cyclus accordingly with one of the cycamore example input files as the input to cyclus
- [x] Does the simulation succeed? Does it fail?
- [x] When it completes, there will be an output file (a database). Find it and see what you can learn about the simulation from the database. You may need an hdf5 viewer or an sqlite viewer installed.

**Comment by eriewski** [comment]
Hi Katy,

After running the xml input files in the cycamore directory, I can't seem to find where the output and results of the run are located. I'm told that the output location is cyclus.sqlite, but I can't seem to access the database. Which hdf5 or sqlite viewer do you think I should install on my virtual machine? When I have this installed, how do I access the output on the database?

**Comment by katyhuff** [comment]
Excellent. It will be a file called "cyclus.sqlite" and will be located in the directory where you executed the command to run the simulation. For sqlite, you'll need an sqlite viewer. I have historically had good luck with sqliteman, but there are probably many other good ones. I encourage you to browse to find your favorite. Note that you should be able to browse appropriate packages with the synaptic package manager (the Applications briefcase in your ubuntu menu).
